### ISSUE TITLE
Bug - undefined serverApiId when overwriting serverApiId in client requests

### ISSUE THREAD

**Issue by Mirasaki** [FlorianSW/cftools-sdk#5]
To reproduce:

```javascript
const { CFToolsClientBuilder, Statistic } = require('cftools-sdk');

const client = new CFToolsClientBuilder()
  .withServerApiId('') // server1
  .withCredentials('', '')
  .build();
  
(async () => {
  // Leaderboard REQ
  const leaderboardData = await client.getLeaderboard({
    order: 'ASC',
    statistic: Statistic.KILLS
  });
  console.log(leaderboardData);
// Expected Result
})();

// But when using
(async () => {
  // Leaderboard REQ
  const leaderboardData = await client.getLeaderboard({
    order: 'ASC',
    statistic: Statistic.KILLS,
    serverApiId: '2' // server2
  });
  console.log(leaderboardData);
})();
```

This is the output
```
/home/mirasaki/projects/node/packages/cftools-sdk/lib/types.js:172
        var _this = _super.call(this, 'ResourceNotFound: ' + url) || this;
                           ^

ResourceNotFound [Error]: ResourceNotFound: https://data.cftools.cloud/v1/server/undefined/leaderboard?stat=kills&order=-1
    at new ResourceNotFound (/home/mirasaki/projects/node/packages/cftools-sdk/lib/types.js:172:28)
    at fromHttpError (/home/mirasaki/projects/node/packages/cftools-sdk/lib/internal/http.js:146:16)
    at GotHttpClient.<anonymous> (/home/mirasaki/projects/node/packages/cftools-sdk/lib/internal/http.js:112:31)
    at step (/home/mirasaki/projects/node/packages/cftools-sdk/lib/internal/http.js:44:23)
    at Object.throw (/home/mirasaki/projects/node/packages/cftools-sdk/lib/internal/http.js:25:53)
    at rejected (/home/mirasaki/projects/node/packages/cftools-sdk/lib/internal/http.js:17:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.3.0
```

This is because the `resolveServerApiId()` function in `src/internal/got/client.ts:500` returns a `string` of the serverApiId when the serverApiId property is overwritten in client requests, instead of a `ServerApiId` class with the `.id` property that is called to get the expected result. Ultimately transforming the API url to `https://data.cftools.cloud/v1/server/undefined/endpoint`

**Comment by FlorianSW** [comment]
The documentation clearly states that the parameter type of `serverApiId` in a request that extends `OverwriteServerApiId` should be `ServerApiId` not `string`:
https://floriansw.github.io/cftools-sdk/interfaces/GetLeaderboardRequest.html#serverApiId

So this more or less looks like a feature request to allow `string` as well, isn't it? What is the use case of that? Why not simply provide the ServerApiId in the first place?

**Comment by Mirasaki** [comment]
True, I definitely missed that. You're right, I can't really think of any use-cases that are worth mentioning. Thanks for clearing up my confusion!

**Comment by FlorianSW** [comment]
Alright, awesome :) Thanks for the feedback. Glad that we could resolve this confusion. I'll go ahead and close this issue then 👍
